sprite $Avtex [16x16/16] {
FFFFFFFFFFFFFFFF
FFF000000FFFFFFF
FFFF000000FFFFFF
FFFFF000000FFFFF
FFFFFF000000FFFF
FFFFFFF000000FFF
FFFFFFFF000000FF
FFFFFFFFFFFFFFFF
FFFFFFFF000000FF
FFFFFFF000000FFF
FFFFFF000000FFFF
FFFFF000000FFFFF
FFFF000000FFFFFF
FFF000000FFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
}

!$AvtexBlue = "092137"
!$AvtexGreen = "2aa154"
!$AvtexBackGround = "White"
!$AvtexFontSize = "18"
!$AvtexFont = "Arial"
!$AvtexThickness = "2"
!$AvtexBarColor ="green";
!$AvtexStartColor ="Green";
!$AvtexEndColor ="Red";
!$AvtexBoxPadding = "10"
!$AvtexDefaultTextAlignment = "center"

skinparam {
	ActivityBackgroundColor	$AvtexGreen
	ActivityBarColor	$AvtexBarColor
	ActivityBorderColor	$AvtexBlue
	ActivityBorderThickness	$AvtexThickness
	ActivityDiamondBackgroundColor	$AvtexGreen
	ActivityDiamondBorderColor	$AvtexBlue
	ActivityDiamondFontColor	$AvtexBlue
	ActivityDiamondFontName	$AvtexFont
	ActivityDiamondFontSize	$AvtexFontSize
	ActivityDiamondFontStyle	normal 
	ActivityEndColor	$AvtexEndColor
	ActivityFontColor	$AvtexBlue
	ActivityFontName	$AvtexFont
	ActivityFontSize	$AvtexFontSize
	ActivityFontStyle	normal 
	ActivityStartColor	$AvtexStartColor
	ActorBackgroundColor	$AvtexGreen
	ActorBorderColor	$AvtexBlue
	ActorFontColor	$AvtexBlue
	ActorFontName	$AvtexFont
	ActorFontSize	$AvtexFontSize
	ActorFontStyle	normal 
	ActorStereotypeFontColor	$AvtexBlue
	ActorStereotypeFontName	$AvtexFont
	ActorStereotypeFontSize	$AvtexFontSize
	ActorStereotypeFontStyle	normal 
	AgentBackgroundColor	$AvtexGreen
	AgentBorderColor	$AvtexBlue
	AgentBorderThickness	$AvtexThickness
	AgentFontColor	$AvtexBlue
	AgentFontName	$AvtexFont
	AgentFontSize	$AvtexFontSize
	AgentFontStyle	normal 
	AgentStereotypeFontColor	$AvtexBlue
	AgentStereotypeFontName	$AvtexFont
	AgentStereotypeFontSize	$AvtexFontSize
	AgentStereotypeFontStyle	normal 
	ArchimateBackgroundColor	$AvtexGreen
	ArchimateBorderColor	$AvtexBlue
	ArchimateBorderThickness	$AvtexThickness
	ArchimateFontColor	$AvtexBlue
	ArchimateFontName	$AvtexFont
	ArchimateFontSize	$AvtexFontSize
	ArchimateFontStyle	normal 
	ArchimateStereotypeFontColor	$AvtexBlue
	ArchimateStereotypeFontName	$AvtexFont
	ArchimateStereotypeFontSize	$AvtexFontSize
	ArchimateStereotypeFontStyle	normal 
	ArrowColor	$AvtexBlue
	ArrowFontColor	$AvtexBlue
	ArrowFontName	$AvtexFont
	ArrowFontSize	$AvtexFontSize
	ArrowFontStyle	normal 
	ArrowHeadColor	$AvtexBlue
	ArrowLollipopColor	$AvtexBlue
	ArrowThickness	$AvtexThickness
	ArtifactBackgroundColor	$AvtexGreen
	ArtifactBorderColor	$AvtexBlue
	ArtifactFontColor	$AvtexBlue
	ArtifactFontName	$AvtexFont
	ArtifactFontSize	$AvtexFontSize
	ArtifactFontStyle	normal 
	ArtifactStereotypeFontColor	$AvtexBlue
	ArtifactStereotypeFontName	$AvtexFont
	ArtifactStereotypeFontSize	$AvtexFontSize
	ArtifactStereotypeFontStyle	normal 
	BackgroundColor	$AvtexBackGround
	BiddableBackgroundColor	$AvtexGreen
	BiddableBorderColor	$AvtexBlue
	BoundaryBackgroundColor	$AvtexGreen
	BoundaryBorderColor	$AvtexBlue
	BoundaryFontColor	$AvtexBlue
	BoundaryFontName	$AvtexFont
	BoundaryFontSize	$AvtexFontSize
	BoundaryFontStyle	normal 
	BoundaryStereotypeFontColor	$AvtexBlue
	BoundaryStereotypeFontName	$AvtexFont
	BoundaryStereotypeFontSize	$AvtexFontSize
	BoundaryStereotypeFontStyle	normal 
	BoxPadding	$AvtexBoxPadding 
	CaptionFontColor	$AvtexBlue
	CaptionFontName	$AvtexFont
	CaptionFontSize	$AvtexFontSize
	CaptionFontStyle	normal 
	CardBackgroundColor	$AvtexGreen
	CardBorderColor	$AvtexBlue
	CardBorderThickness	$AvtexThickness
	CardFontColor	$AvtexBlue
	CardFontName	$AvtexFont
	CardFontSize	$AvtexFontSize
	CardFontStyle	normal 
	CardStereotypeFontColor	$AvtexBlue
	CardStereotypeFontName	$AvtexFont
	CardStereotypeFontSize	$AvtexFontSize
	CardStereotypeFontStyle	normal 
	CircledCharacterFontColor	$AvtexBlue
	CircledCharacterFontName	$AvtexFont
	CircledCharacterFontSize	$AvtexFontSize
	CircledCharacterFontStyle	normal 
	ClassAttributeFontColor	$AvtexBlue
	ClassAttributeFontName	$AvtexFont
	ClassAttributeFontSize	$AvtexFontSize
	ClassAttributeFontStyle	normal 
	ClassAttributeIconSize	1$AvtexThickness
	ClassBackgroundColor	$AvtexGreen
	ClassBorderColor	$AvtexBlue
	ClassBorderThickness	$AvtexThickness
	ClassFontColor	$AvtexBlue
	ClassFontName	$AvtexFont
	ClassFontSize	$AvtexFontSize
	ClassFontStyle	normal 
	ClassHeaderBackgroundColor	$AvtexGreen
	ClassStereotypeFontColor	$AvtexBlue
	ClassStereotypeFontName	$AvtexFont
	ClassStereotypeFontSize	$AvtexFontSize
	ClassStereotypeFontStyle	normal 
	CloudBackgroundColor	$AvtexBackGround
	CloudBorderColor	$AvtexBlue
	CloudFontColor	$AvtexBlue
	CloudFontName	$AvtexFont
	CloudFontSize	$AvtexFontSize
	CloudFontStyle	normal 
	CloudStereotypeFontColor	$AvtexBlue
	CloudStereotypeFontName	$AvtexFont
	CloudStereotypeFontSize	$AvtexFontSize
	CloudStereotypeFontStyle	normal 
	CollectionsBackgroundColor	$AvtexGreen
	CollectionsBorderColor	$AvtexBlue
	ColorArrowSeparationSpace	$AvtexBlue
	ComponentBackgroundColor	$AvtexGreen
	ComponentBorderColor	$AvtexBlue
	ComponentBorderThickness	$AvtexThickness
	ComponentFontColor	$AvtexBlue
	ComponentFontName	$AvtexFont
	ComponentFontSize	$AvtexFontSize
	ComponentFontStyle	normal 
	ComponentStereotypeFontColor	$AvtexBlue
	ComponentStereotypeFontName	$AvtexFont
	ComponentStereotypeFontSize	$AvtexFontSize
	ComponentStereotypeFontStyle	normal 
	ComponentStyle	normal 
	ConditionEndStyle	normal 
	ConditionStyle	normal 
	ControlBackgroundColor	$AvtexGreen
	ControlBorderColor	$AvtexBlue
	ControlFontColor	$AvtexBlue
	ControlFontName	$AvtexFont
	ControlFontSize	$AvtexFontSize
	ControlFontStyle	normal 
	ControlStereotypeFontColor	$AvtexBlue
	ControlStereotypeFontName	$AvtexFont
	ControlStereotypeFontSize	$AvtexFontSize
	ControlStereotypeFontStyle	normal 
	DatabaseBackgroundColor	$AvtexBackGround
	DatabaseBorderColor	$AvtexBlue
	DatabaseFontColor	$AvtexBlue
	DatabaseFontName	$AvtexFont
	DatabaseFontSize	$AvtexFontSize
	DatabaseFontStyle	normal 
	DatabaseStereotypeFontColor	$AvtexBlue
	DatabaseStereotypeFontName	$AvtexFont
	DatabaseStereotypeFontSize	$AvtexFontSize
	DatabaseStereotypeFontStyle	normal 
	DefaultFontColor	$AvtexBlue
	DefaultFontName	$AvtexFont
	DefaultFontSize	$AvtexFontSize
	DefaultFontStyle	normal 
	DefaultMonospacedFontName	$AvtexFont
	DefaultTextAlignment	$AvtexDefaultTextAlignment
	DesignedBackgroundColor	$AvtexGreen
	DesignedBorderColor	$AvtexBlue
	DesignedDomainBorderThickness	$AvtexThickness
	DesignedDomainFontColor	$AvtexBlue
	DesignedDomainFontName	$AvtexFont
	DesignedDomainFontSize	$AvtexFontSize
	DesignedDomainFontStyle	normal 
	DesignedDomainStereotypeFontColor	$AvtexBlue
	DesignedDomainStereotypeFontName	$AvtexFont
	DesignedDomainStereotypeFontSize	$AvtexFontSize
	DesignedDomainStereotypeFontStyle	normal 
	DiagramBorderColor	$AvtexBlue
	DiagramBorderThickness	$AvtexThickness
	DomainBackgroundColor	$AvtexGreen
	DomainBorderColor	$AvtexBlue
	DomainBorderThickness	$AvtexThickness
	DomainFontColor	$AvtexBlue
	DomainFontName	$AvtexFont
	DomainFontSize	$AvtexFontSize
	DomainFontStyle	normal 
	DomainStereotypeFontColor	$AvtexBlue
	DomainStereotypeFontName	$AvtexFont
	DomainStereotypeFontSize	$AvtexFontSize
	DomainStereotypeFontStyle	normal 
	EntityBackgroundColor	$AvtexGreen
	EntityBorderColor	$AvtexBlue
	EntityFontColor	$AvtexBlue
	EntityFontName	$AvtexFont
	EntityFontSize	$AvtexFontSize
	EntityFontStyle	normal 
	EntityStereotypeFontColor	$AvtexBlue
	EntityStereotypeFontName	$AvtexFont
	EntityStereotypeFontSize	$AvtexFontSize
	EntityStereotypeFontStyle	normal 
	EnumBackgroundColor	$AvtexGreen
	FileBackgroundColor	$AvtexGreen
	FileBorderColor	$AvtexBlue
	FileFontColor	$AvtexBlue
	FileFontName	$AvtexFont
	FileFontSize	$AvtexFontSize
	FileFontStyle	normal 
	FileStereotypeFontColor	$AvtexBlue
	FileStereotypeFontName	$AvtexFont
	FileStereotypeFontSize	$AvtexFontSize
	FileStereotypeFontStyle	normal 
	FolderBackgroundColor	$AvtexGreen
	FolderBorderColor	$AvtexBlue
	FolderFontColor	$AvtexBlue
	FolderFontName	$AvtexFont
	FolderFontSize	$AvtexFontSize
	FolderFontStyle	normal 
	FolderStereotypeFontColor	$AvtexBlue
	FolderStereotypeFontName	$AvtexFont
	FolderStereotypeFontSize	$AvtexFontSize
	FolderStereotypeFontStyle	normal 
	FooterFontColor	$AvtexBlue
	FooterFontName	$AvtexFont
	FooterFontSize	$AvtexFontSize
	FooterFontStyle	normal 
	FrameBackgroundColor	$AvtexGreen
	FrameBorderColor	$AvtexBlue
	FrameFontColor	$AvtexBlue
	FrameFontName	$AvtexFont
	FrameFontSize	$AvtexFontSize
	FrameFontStyle	normal 
	FrameStereotypeFontColor	$AvtexBlue
	FrameStereotypeFontName	$AvtexFont
	FrameStereotypeFontSize	$AvtexFontSize
	FrameStereotypeFontStyle	normal 
	HeaderFontColor	$AvtexBlue
	HeaderFontName	$AvtexFont
	HeaderFontSize	$AvtexFontSize
	HeaderFontStyle	normal 
	HyperlinkColor	$AvtexBlue
	IconIEMandatoryColor	$AvtexBlue
	IconPackageBackgroundColor	$AvtexGreen
	IconPackageColor	$AvtexBlue
	IconPrivateBackgroundColor	$AvtexGreen
	IconPrivateColor	$AvtexBlue
	IconProtectedBackgroundColor	$AvtexGreen
	IconProtectedColor	$AvtexBlue
	IconPublicBackgroundColor	$AvtexGreen
	IconPublicColor	$AvtexBlue
	InterfaceBackgroundColor	$AvtexGreen
	InterfaceBorderColor	$AvtexBlue
	InterfaceFontColor	$AvtexBlue
	InterfaceFontName	$AvtexFont
	InterfaceFontSize	$AvtexFontSize
	InterfaceFontStyle	normal 
	InterfaceStereotypeFontColor	$AvtexBlue
	InterfaceStereotypeFontName	$AvtexFont
	InterfaceStereotypeFontSize	$AvtexFontSize
	InterfaceStereotypeFontStyle	normal 
	LegendBackgroundColor	$AvtexGreen
	LegendBorderColor	$AvtexBlue
	LegendBorderThickness	$AvtexThickness
	LegendFontColor	$AvtexBlue
	LegendFontName	$AvtexFont
	LegendFontSize	$AvtexFontSize
	LegendFontStyle	normal 
	LexicalBackgroundColor	$AvtexGreen
	LexicalBorderColor	$AvtexBlue
	MachineBackgroundColor	$AvtexGreen
	MachineBorderColor	$AvtexBlue
	MachineBorderThickness	$AvtexThickness
	MachineFontColor	$AvtexBlue
	MachineFontName	$AvtexFont
	MachineFontSize	$AvtexFontSize
	MachineFontStyle	normal 
	MachineStereotypeFontColor	$AvtexBlue
	MachineStereotypeFontName	$AvtexFont
	MachineStereotypeFontSize	$AvtexFontSize
	MachineStereotypeFontStyle	normal 
	NodeBackgroundColor	$AvtexBackGround
	NodeBorderColor	$AvtexBlue
	NodeFontColor	$AvtexBlue
	NodeFontName	$AvtexFont
	NodeFontSize	$AvtexFontSize
	NodeFontStyle	normal 
	NodeStereotypeFontColor	$AvtexBlue
	NodeStereotypeFontName	$AvtexFont
	NodeStereotypeFontSize	$AvtexFontSize
	NodeStereotypeFontStyle	normal 
	NoteBackgroundColor	$AvtexGreen
	NoteBorderColor	$AvtexBlue
	NoteBorderThickness	$AvtexThickness
	NoteFontColor	$AvtexBlue
	NoteFontName	$AvtexFont
	NoteFontSize	$AvtexFontSize
	NoteFontStyle	normal 
	NoteShadowing	TRUE
	NoteTextAlignment	Center
	ObjectAttributeFontColor	$AvtexBlue
	ObjectAttributeFontName	$AvtexFont
	ObjectAttributeFontSize	$AvtexFontSize
	ObjectAttributeFontStyle	normal 
	ObjectBackgroundColor	$AvtexGreen
	ObjectBorderColor	$AvtexBlue
	ObjectBorderThickness	$AvtexThickness
	ObjectFontColor	$AvtexBlue
	ObjectFontName	$AvtexFont
	ObjectFontSize	$AvtexFontSize
	ObjectFontStyle	normal 
	ObjectStereotypeFontColor	$AvtexBlue
	ObjectStereotypeFontName	$AvtexFont
	ObjectStereotypeFontSize	$AvtexFontSize
	ObjectStereotypeFontStyle	normal 
	PackageBackgroundColor	$AvtexBackGround
	PackageBorderColor	$AvtexBlue
	PackageBorderThickness	$AvtexThickness
	PackageFontColor	$AvtexBlue
	PackageFontName	$AvtexFont
	PackageFontSize	$AvtexFontSize
	PackageFontStyle	normal 
	PackageStereotypeFontColor	$AvtexBlue
	PackageStereotypeFontName	$AvtexFont
	PackageStereotypeFontSize	$AvtexFontSize
	PackageStereotypeFontStyle	normal 
	PackageStyle	Bold
	PackageTitleAlignment	left
	PageBorderColor	$AvtexBlue
	PageExternalColor	$AvtexBlue
	PageMargin	5
	ParticipantBackgroundColor	$AvtexGreen
	ParticipantBorderColor	$AvtexBlue
	ParticipantFontColor	$AvtexBlue
	ParticipantFontName	$AvtexFont
	ParticipantFontSize	$AvtexFontSize
	ParticipantFontStyle	normal 
	ParticipantPadding	100
	ParticipantStereotypeFontColor	$AvtexBlue
	ParticipantStereotypeFontName	$AvtexFont
	ParticipantStereotypeFontSize	$AvtexFontSize
	ParticipantStereotypeFontStyle	normal 
	PartitionBackgroundColor	$AvtexGreen
	PartitionBorderColor	$AvtexBlue
	PartitionBorderThickness	$AvtexThickness
	PartitionFontColor	$AvtexBlue
	PartitionFontName	$AvtexFont
	PartitionFontSize	$AvtexFontSize
	PartitionFontStyle	normal 
	PathHoverColor	$AvtexBlue
	QueueBackgroundColor	$AvtexGreen
	QueueBorderColor	$AvtexBlue
	QueueBorderThickness	$AvtexThickness
	QueueFontColor	$AvtexBlue
	QueueFontName	$AvtexFont
	QueueFontSize	$AvtexFontSize
	QueueFontStyle	normal 
	QueueStereotypeFontColor	$AvtexBlue
	QueueStereotypeFontName	$AvtexFont
	QueueStereotypeFontSize	$AvtexFontSize
	QueueStereotypeFontStyle	normal 
	RectangleBackgroundColor	$AvtexGreen
	RectangleBorderColor	$AvtexBlue
	RectangleBorderThickness	$AvtexThickness
	RectangleFontColor	$AvtexBlue
	RectangleFontName	$AvtexFont
	RectangleFontSize	$AvtexFontSize
	RectangleFontStyle	normal 
	RectangleStereotypeFontColor	$AvtexBlue
	RectangleStereotypeFontName	$AvtexFont
	RectangleStereotypeFontSize	$AvtexFontSize
	RectangleStereotypeFontStyle	normal 
	RequirementBackgroundColor	$AvtexGreen
	RequirementBorderColor	$AvtexBlue
	RequirementBorderThickness	$AvtexThickness
	RequirementFontColor	$AvtexBlue
	RequirementFontName	$AvtexFont
	RequirementFontSize	$AvtexFontSize
	RequirementFontStyle	normal 
	RequirementStereotypeFontColor	$AvtexBlue
	RequirementStereotypeFontName	$AvtexFont
	RequirementStereotypeFontSize	$AvtexFontSize
	RequirementStereotypeFontStyle	normal 
	RoundCorner	TRUE
	SequenceActorBorderThickness	$AvtexThickness
	SequenceArrowThickness	$AvtexThickness
	SequenceBoxBackgroundColor	$AvtexGreen
	SequenceBoxBorderColor	$AvtexBlue
	SequenceBoxFontColor	$AvtexBlue
	SequenceBoxFontName	$AvtexFont
	SequenceBoxFontSize	$AvtexFontSize
	SequenceBoxFontStyle	normal 
	SequenceDelayFontColor	$AvtexBlue
	SequenceDelayFontName	$AvtexFont
	SequenceDelayFontSize	$AvtexFontSize
	SequenceDelayFontStyle	normal 
	SequenceDividerBackgroundColor	$AvtexGreen
	SequenceDividerBorderColor	$AvtexBlue
	SequenceDividerBorderThickness	$AvtexThickness
	SequenceDividerFontColor	$AvtexBlue
	SequenceDividerFontName	$AvtexFont
	SequenceDividerFontSize	$AvtexFontSize
	SequenceDividerFontStyle	normal 
	SequenceGroupBackgroundColor	$AvtexGreen
	SequenceGroupBodyBackgroundColor	$AvtexGreen
	SequenceGroupBorderColor	$AvtexBlue
	SequenceGroupBorderThickness	$AvtexThickness
	SequenceGroupFontColor	$AvtexBlue
	SequenceGroupFontName	$AvtexFont
	SequenceGroupFontSize	$AvtexFontSize
	SequenceGroupFontStyle	normal 
	SequenceGroupHeaderFontColor	$AvtexBlue
	SequenceGroupHeaderFontName	$AvtexFont
	SequenceGroupHeaderFontSize	$AvtexFontSize
	SequenceGroupHeaderFontStyle	normal 
	SequenceLifeLineBackgroundColor	$AvtexGreen
	SequenceLifeLineBorderColor	$AvtexBlue
	SequenceLifeLineBorderThickness	$AvtexThickness
	SequenceMessageAlignment	center
	SequenceMessageTextAlignment	center
	SequenceNewpageSeparatorColor	$AvtexBlue
	SequenceParticipantBorderThickness	$AvtexThickness
	SequenceReferenceBackgroundColor	$AvtexGreen
	SequenceReferenceBorderColor	$AvtexBlue
	SequenceReferenceBorderThickness	$AvtexThickness
	SequenceReferenceFontColor	$AvtexBlue
	SequenceReferenceFontName	$AvtexFont
	SequenceReferenceFontSize	$AvtexFontSize
	SequenceReferenceFontStyle	normal 
	SequenceReferenceHeaderBackgroundColor	$AvtexGreen
	SequenceStereotypeFontColor	$AvtexBlue
	SequenceStereotypeFontName	$AvtexFont
	SequenceStereotypeFontSize	$AvtexFontSize
	SequenceStereotypeFontStyle	normal 
	Shadowing	TRUE
	StackBackgroundColor	$AvtexGreen
	StackBorderColor	$AvtexBlue
	StackFontColor	$AvtexBlue
	StackFontName	$AvtexFont
	StackFontSize	$AvtexFontSize
	StackFontStyle	normal 
	StackStereotypeFontColor	$AvtexBlue
	StackStereotypeFontName	$AvtexFont
	StackStereotypeFontSize	$AvtexFontSize
	StackStereotypeFontStyle	normal 
	StateAttributeFontColor	$AvtexBlue
	StateAttributeFontName	$AvtexFont
	StateAttributeFontSize	$AvtexFontSize
	StateAttributeFontStyle	normal 
	StateBackgroundColor	$AvtexGreen
	StateBorderColor	$AvtexBlue
	StateEndColor	$AvtexBlue
	StateFontColor	$AvtexBlue
	StateFontName	$AvtexFont
	StateFontSize	$AvtexFontSize
	StateFontStyle	normal 
	StateStartColor	$AvtexBlue
	StereotypeABackgroundColor	$AvtexGreen
	StereotypeABorderColor	$AvtexBlue
	StereotypeCBackgroundColor	$AvtexGreen
	StereotypeCBorderColor	$AvtexBlue
	StereotypeEBackgroundColor	$AvtexGreen
	StereotypeEBorderColor	$AvtexBlue
	StereotypeIBackgroundColor	$AvtexGreen
	StereotypeIBorderColor	$AvtexBlue
	StereotypeNBackgroundColor	$AvtexGreen
	StereotypeNBorderColor	$AvtexBlue
	StorageBackgroundColor	$AvtexGreen
	StorageBorderColor	$AvtexBlue
	StorageFontColor	$AvtexBlue
	StorageFontName	$AvtexFont
	StorageFontSize	$AvtexFontSize
	StorageFontStyle	normal 
	StorageStereotypeFontColor	$AvtexBlue
	StorageStereotypeFontName	$AvtexFont
	StorageStereotypeFontSize	$AvtexFontSize
	StorageStereotypeFontStyle	normal 
	Style	normal 
	SwimlaneBorderColor	$AvtexBlue
	SwimlaneBorderThickness	$AvtexThickness
	SwimlaneTitleBackgroundColor	$AvtexGreen
	SwimlaneTitleFontColor	$AvtexBlue
	SwimlaneTitleFontName	$AvtexFont
	SwimlaneTitleFontSize	$AvtexFontSize
	SwimlaneTitleFontStyle	normal 
	TabSize	3
	TimingFontColor	$AvtexBlue
	TimingFontName	$AvtexFont
	TimingFontSize	$AvtexFontSize
	TimingFontStyle	normal 
	TitleBackgroundColor	$AvtexGreen
	TitleBorderColor	$AvtexBlue
	TitleBorderRoundCorner	TRUE
	TitleBorderThickness	$AvtexThickness
	TitleFontColor	$AvtexBlue
	TitleFontName	$AvtexFont
	TitleFontSize	$AvtexFontSize
	TitleFontStyle	normal 
	UsecaseBackgroundColor	$AvtexGreen
	UsecaseBorderColor	$AvtexBlue
	UsecaseBorderThickness	$AvtexThickness
	UsecaseFontColor	$AvtexBlue
	UsecaseFontName	$AvtexFont
	UsecaseFontSize	$AvtexFontSize
	UsecaseFontStyle	normal 
	UsecaseStereotypeFontColor	$AvtexBlue
	UsecaseStereotypeFontName	$AvtexFont
	UsecaseStereotypeFontSize	$AvtexFontSize
	UsecaseStereotypeFontStyle	normal 
}
