sprite $Avtex [16x16/16] {
FFFFFFFFFFFFFFFF
FFF000000FFFFFFF
FFFF000000FFFFFF
FFFFF000000FFFFF
FFFFFF000000FFFF
FFFFFFF000000FFF
FFFFFFFF000000FF
FFFFFFFFFFFFFFFF
FFFFFFFF000000FF
FFFFFFF000000FFF
FFFFFF000000FFFF
FFFFF000000FFFFF
FFFF000000FFFFFF
FFF000000FFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
}
skinparam {
	ActivityBackgroundColor	2aa154
	ActivityBarColor	Green
	ActivityBorderColor	092137
	ActivityBorderThickness	2
	ActivityDiamondBackgroundColor	2aa154
	ActivityDiamondBorderColor	092137
	ActivityDiamondFontColor	092137
	ActivityDiamondFontName	Arial
	ActivityDiamondFontSize	18
	ActivityDiamondFontStyle	normal 
	ActivityEndColor	Red
	ActivityFontColor	092137
	ActivityFontName	Arial
	ActivityFontSize	18
	ActivityFontStyle	normal 
	ActivityStartColor	Green
	ActorBackgroundColor	2aa154
	ActorBorderColor	092137
	ActorFontColor	092137
	ActorFontName	Arial
	ActorFontSize	18
	ActorFontStyle	normal 
	ActorStereotypeFontColor	092137
	ActorStereotypeFontName	Arial
	ActorStereotypeFontSize	18
	ActorStereotypeFontStyle	normal 
	AgentBackgroundColor	2aa154
	AgentBorderColor	092137
	AgentBorderThickness	2
	AgentFontColor	092137
	AgentFontName	Arial
	AgentFontSize	18
	AgentFontStyle	normal 
	AgentStereotypeFontColor	092137
	AgentStereotypeFontName	Arial
	AgentStereotypeFontSize	18
	AgentStereotypeFontStyle	normal 
	ArchimateBackgroundColor	2aa154
	ArchimateBorderColor	092137
	ArchimateBorderThickness	2
	ArchimateFontColor	092137
	ArchimateFontName	Arial
	ArchimateFontSize	18
	ArchimateFontStyle	normal 
	ArchimateStereotypeFontColor	092137
	ArchimateStereotypeFontName	Arial
	ArchimateStereotypeFontSize	18
	ArchimateStereotypeFontStyle	normal 
	ArrowColor	092137
	ArrowFontColor	092137
	ArrowFontName	Arial
	ArrowFontSize	18
	ArrowFontStyle	normal 
	ArrowHeadColor	092137
	ArrowLollipopColor	092137
	ArrowThickness	2
	ArtifactBackgroundColor	2aa154
	ArtifactBorderColor	092137
	ArtifactFontColor	092137
	ArtifactFontName	Arial
	ArtifactFontSize	18
	ArtifactFontStyle	normal 
	ArtifactStereotypeFontColor	092137
	ArtifactStereotypeFontName	Arial
	ArtifactStereotypeFontSize	18
	ArtifactStereotypeFontStyle	normal 
	BackgroundColor	White
	BiddableBackgroundColor	2aa154
	BiddableBorderColor	092137
	BoundaryBackgroundColor	2aa154
	BoundaryBorderColor	092137
	BoundaryFontColor	092137
	BoundaryFontName	Arial
	BoundaryFontSize	18
	BoundaryFontStyle	normal 
	BoundaryStereotypeFontColor	092137
	BoundaryStereotypeFontName	Arial
	BoundaryStereotypeFontSize	18
	BoundaryStereotypeFontStyle	normal 
	BoxPadding	10
	CaptionFontColor	092137
	CaptionFontName	Arial
	CaptionFontSize	18
	CaptionFontStyle	normal 
	CardBackgroundColor	2aa154
	CardBorderColor	092137
	CardBorderThickness	2
	CardFontColor	092137
	CardFontName	Arial
	CardFontSize	18
	CardFontStyle	normal 
	CardStereotypeFontColor	092137
	CardStereotypeFontName	Arial
	CardStereotypeFontSize	18
	CardStereotypeFontStyle	normal 
	CircledCharacterFontColor	092137
	CircledCharacterFontName	Arial
	CircledCharacterFontSize	18
	CircledCharacterFontStyle	normal 
	ClassAttributeFontColor	092137
	ClassAttributeFontName	Arial
	ClassAttributeFontSize	18
	ClassAttributeFontStyle	normal 
	ClassAttributeIconSize	12
	ClassBackgroundColor	2aa154
	ClassBorderColor	092137
	ClassBorderThickness	2
	ClassFontColor	092137
	ClassFontName	Arial
	ClassFontSize	18
	ClassFontStyle	normal 
	ClassHeaderBackgroundColor	2aa154
	ClassStereotypeFontColor	092137
	ClassStereotypeFontName	Arial
	ClassStereotypeFontSize	18
	ClassStereotypeFontStyle	normal 
	CloudBackgroundColor	white
	CloudBorderColor	092137
	CloudFontColor	092137
	CloudFontName	Arial
	CloudFontSize	18
	CloudFontStyle	normal 
	CloudStereotypeFontColor	092137
	CloudStereotypeFontName	Arial
	CloudStereotypeFontSize	18
	CloudStereotypeFontStyle	normal 
	CollectionsBackgroundColor	2aa154
	CollectionsBorderColor	092137
	ColorArrowSeparationSpace	092137
	ComponentBackgroundColor	2aa154
	ComponentBorderColor	092137
	ComponentBorderThickness	2
	ComponentFontColor	092137
	ComponentFontName	Arial
	ComponentFontSize	18
	ComponentFontStyle	normal 
	ComponentStereotypeFontColor	092137
	ComponentStereotypeFontName	Arial
	ComponentStereotypeFontSize	18
	ComponentStereotypeFontStyle	normal 
	ComponentStyle	normal 
	ConditionEndStyle	normal 
	ConditionStyle	normal 
	ControlBackgroundColor	2aa154
	ControlBorderColor	092137
	ControlFontColor	092137
	ControlFontName	Arial
	ControlFontSize	18
	ControlFontStyle	normal 
	ControlStereotypeFontColor	092137
	ControlStereotypeFontName	Arial
	ControlStereotypeFontSize	18
	ControlStereotypeFontStyle	normal 
	DatabaseBackgroundColor	White
	DatabaseBorderColor	092137
	DatabaseFontColor	092137
	DatabaseFontName	Arial
	DatabaseFontSize	18
	DatabaseFontStyle	normal 
	DatabaseStereotypeFontColor	092137
	DatabaseStereotypeFontName	Arial
	DatabaseStereotypeFontSize	18
	DatabaseStereotypeFontStyle	normal 
	DefaultFontColor	092137
	DefaultFontName	Arial
	DefaultFontSize	18
	DefaultFontStyle	normal 
	DefaultMonospacedFontName	Arial
	DefaultTextAlignment	center
	DesignedBackgroundColor	2aa154
	DesignedBorderColor	092137
	DesignedDomainBorderThickness	2
	DesignedDomainFontColor	092137
	DesignedDomainFontName	Arial
	DesignedDomainFontSize	18
	DesignedDomainFontStyle	normal 
	DesignedDomainStereotypeFontColor	092137
	DesignedDomainStereotypeFontName	Arial
	DesignedDomainStereotypeFontSize	18
	DesignedDomainStereotypeFontStyle	normal 
	DiagramBorderColor	092137
	DiagramBorderThickness	2
	DomainBackgroundColor	2aa154
	DomainBorderColor	092137
	DomainBorderThickness	2
	DomainFontColor	092137
	DomainFontName	Arial
	DomainFontSize	18
	DomainFontStyle	normal 
	DomainStereotypeFontColor	092137
	DomainStereotypeFontName	Arial
	DomainStereotypeFontSize	18
	DomainStereotypeFontStyle	normal 
	EntityBackgroundColor	2aa154
	EntityBorderColor	092137
	EntityFontColor	092137
	EntityFontName	Arial
	EntityFontSize	18
	EntityFontStyle	normal 
	EntityStereotypeFontColor	092137
	EntityStereotypeFontName	Arial
	EntityStereotypeFontSize	18
	EntityStereotypeFontStyle	normal 
	EnumBackgroundColor	2aa154
	FileBackgroundColor	2aa154
	FileBorderColor	092137
	FileFontColor	092137
	FileFontName	Arial
	FileFontSize	18
	FileFontStyle	normal 
	FileStereotypeFontColor	092137
	FileStereotypeFontName	Arial
	FileStereotypeFontSize	18
	FileStereotypeFontStyle	normal 
	FolderBackgroundColor	2aa154
	FolderBorderColor	092137
	FolderFontColor	092137
	FolderFontName	Arial
	FolderFontSize	18
	FolderFontStyle	normal 
	FolderStereotypeFontColor	092137
	FolderStereotypeFontName	Arial
	FolderStereotypeFontSize	18
	FolderStereotypeFontStyle	normal 
	FooterFontColor	092137
	FooterFontName	Arial
	FooterFontSize	18
	FooterFontStyle	normal 
	FrameBackgroundColor	2aa154
	FrameBorderColor	092137
	FrameFontColor	092137
	FrameFontName	Arial
	FrameFontSize	18
	FrameFontStyle	normal 
	FrameStereotypeFontColor	092137
	FrameStereotypeFontName	Arial
	FrameStereotypeFontSize	18
	FrameStereotypeFontStyle	normal 
	HeaderFontColor	092137
	HeaderFontName	Arial
	HeaderFontSize	18
	HeaderFontStyle	normal 
	HyperlinkColor	092137
	IconIEMandatoryColor	092137
	IconPackageBackgroundColor	2aa154
	IconPackageColor	092137
	IconPrivateBackgroundColor	2aa154
	IconPrivateColor	092137
	IconProtectedBackgroundColor	2aa154
	IconProtectedColor	092137
	IconPublicBackgroundColor	2aa154
	IconPublicColor	092137
	InterfaceBackgroundColor	2aa154
	InterfaceBorderColor	092137
	InterfaceFontColor	092137
	InterfaceFontName	Arial
	InterfaceFontSize	18
	InterfaceFontStyle	normal 
	InterfaceStereotypeFontColor	092137
	InterfaceStereotypeFontName	Arial
	InterfaceStereotypeFontSize	18
	InterfaceStereotypeFontStyle	normal 
	LegendBackgroundColor	2aa154
	LegendBorderColor	092137
	LegendBorderThickness	2
	LegendFontColor	092137
	LegendFontName	Arial
	LegendFontSize	18
	LegendFontStyle	normal 
	LexicalBackgroundColor	2aa154
	LexicalBorderColor	092137
	MachineBackgroundColor	2aa154
	MachineBorderColor	092137
	MachineBorderThickness	2
	MachineFontColor	092137
	MachineFontName	Arial
	MachineFontSize	18
	MachineFontStyle	normal 
	MachineStereotypeFontColor	092137
	MachineStereotypeFontName	Arial
	MachineStereotypeFontSize	18
	MachineStereotypeFontStyle	normal 
	NodeBackgroundColor	White
	NodeBorderColor	092137
	NodeFontColor	092137
	NodeFontName	Arial
	NodeFontSize	18
	NodeFontStyle	normal 
	NodeStereotypeFontColor	092137
	NodeStereotypeFontName	Arial
	NodeStereotypeFontSize	18
	NodeStereotypeFontStyle	normal 
	NoteBackgroundColor	2aa154
	NoteBorderColor	092137
	NoteBorderThickness	2
	NoteFontColor	092137
	NoteFontName	Arial
	NoteFontSize	18
	NoteFontStyle	normal 
	NoteShadowing	TRUE
	NoteTextAlignment	Center
	ObjectAttributeFontColor	092137
	ObjectAttributeFontName	Arial
	ObjectAttributeFontSize	18
	ObjectAttributeFontStyle	normal 
	ObjectBackgroundColor	2aa154
	ObjectBorderColor	092137
	ObjectBorderThickness	2
	ObjectFontColor	092137
	ObjectFontName	Arial
	ObjectFontSize	18
	ObjectFontStyle	normal 
	ObjectStereotypeFontColor	092137
	ObjectStereotypeFontName	Arial
	ObjectStereotypeFontSize	18
	ObjectStereotypeFontStyle	normal 
	PackageBackgroundColor	white
	PackageBorderColor	092137
	PackageBorderThickness	2
	PackageFontColor	092137
	PackageFontName	Arial
	PackageFontSize	18
	PackageFontStyle	normal 
	PackageStereotypeFontColor	092137
	PackageStereotypeFontName	Arial
	PackageStereotypeFontSize	18
	PackageStereotypeFontStyle	normal 
	PackageStyle	Bold
	PackageTitleAlignment	left
	PageBorderColor	092137
	PageExternalColor	092137
	PageMargin	5
	ParticipantBackgroundColor	2aa154
	ParticipantBorderColor	092137
	ParticipantFontColor	092137
	ParticipantFontName	Arial
	ParticipantFontSize	18
	ParticipantFontStyle	normal 
	ParticipantPadding	100
	ParticipantStereotypeFontColor	092137
	ParticipantStereotypeFontName	Arial
	ParticipantStereotypeFontSize	18
	ParticipantStereotypeFontStyle	normal 
	PartitionBackgroundColor	2aa154
	PartitionBorderColor	092137
	PartitionBorderThickness	2
	PartitionFontColor	092137
	PartitionFontName	Arial
	PartitionFontSize	18
	PartitionFontStyle	normal 
	PathHoverColor	092137
	QueueBackgroundColor	2aa154
	QueueBorderColor	092137
	QueueBorderThickness	2
	QueueFontColor	092137
	QueueFontName	Arial
	QueueFontSize	18
	QueueFontStyle	normal 
	QueueStereotypeFontColor	092137
	QueueStereotypeFontName	Arial
	QueueStereotypeFontSize	18
	QueueStereotypeFontStyle	normal 
	RectangleBackgroundColor	2aa154
	RectangleBorderColor	092137
	RectangleBorderThickness	2
	RectangleFontColor	092137
	RectangleFontName	Arial
	RectangleFontSize	18
	RectangleFontStyle	normal 
	RectangleStereotypeFontColor	092137
	RectangleStereotypeFontName	Arial
	RectangleStereotypeFontSize	18
	RectangleStereotypeFontStyle	normal 
	RequirementBackgroundColor	2aa154
	RequirementBorderColor	092137
	RequirementBorderThickness	2
	RequirementFontColor	092137
	RequirementFontName	Arial
	RequirementFontSize	18
	RequirementFontStyle	normal 
	RequirementStereotypeFontColor	092137
	RequirementStereotypeFontName	Arial
	RequirementStereotypeFontSize	18
	RequirementStereotypeFontStyle	normal 
	RoundCorner	TRUE
	SequenceActorBorderThickness	2
	SequenceArrowThickness	2
	SequenceBoxBackgroundColor	2aa154
	SequenceBoxBorderColor	092137
	SequenceBoxFontColor	092137
	SequenceBoxFontName	Arial
	SequenceBoxFontSize	18
	SequenceBoxFontStyle	normal 
	SequenceDelayFontColor	092137
	SequenceDelayFontName	Arial
	SequenceDelayFontSize	18
	SequenceDelayFontStyle	normal 
	SequenceDividerBackgroundColor	2aa154
	SequenceDividerBorderColor	092137
	SequenceDividerBorderThickness	2
	SequenceDividerFontColor	092137
	SequenceDividerFontName	Arial
	SequenceDividerFontSize	18
	SequenceDividerFontStyle	normal 
	SequenceGroupBackgroundColor	2aa154
	SequenceGroupBodyBackgroundColor	2aa154
	SequenceGroupBorderColor	092137
	SequenceGroupBorderThickness	2
	SequenceGroupFontColor	092137
	SequenceGroupFontName	Arial
	SequenceGroupFontSize	18
	SequenceGroupFontStyle	normal 
	SequenceGroupHeaderFontColor	092137
	SequenceGroupHeaderFontName	Arial
	SequenceGroupHeaderFontSize	18
	SequenceGroupHeaderFontStyle	normal 
	SequenceLifeLineBackgroundColor	2aa154
	SequenceLifeLineBorderColor	092137
	SequenceLifeLineBorderThickness	2
	SequenceMessageAlignment	center
	SequenceMessageTextAlignment	center
	SequenceNewpageSeparatorColor	092137
	SequenceParticipantBorderThickness	2
	SequenceReferenceBackgroundColor	2aa154
	SequenceReferenceBorderColor	092137
	SequenceReferenceBorderThickness	2
	SequenceReferenceFontColor	092137
	SequenceReferenceFontName	Arial
	SequenceReferenceFontSize	18
	SequenceReferenceFontStyle	normal 
	SequenceReferenceHeaderBackgroundColor	2aa154
	SequenceStereotypeFontColor	092137
	SequenceStereotypeFontName	Arial
	SequenceStereotypeFontSize	18
	SequenceStereotypeFontStyle	normal 
	Shadowing	TRUE
	StackBackgroundColor	2aa154
	StackBorderColor	092137
	StackFontColor	092137
	StackFontName	Arial
	StackFontSize	18
	StackFontStyle	normal 
	StackStereotypeFontColor	092137
	StackStereotypeFontName	Arial
	StackStereotypeFontSize	18
	StackStereotypeFontStyle	normal 
	StateAttributeFontColor	092137
	StateAttributeFontName	Arial
	StateAttributeFontSize	18
	StateAttributeFontStyle	normal 
	StateBackgroundColor	2aa154
	StateBorderColor	092137
	StateEndColor	092137
	StateFontColor	092137
	StateFontName	Arial
	StateFontSize	18
	StateFontStyle	normal 
	StateStartColor	092137
	StereotypeABackgroundColor	2aa154
	StereotypeABorderColor	092137
	StereotypeCBackgroundColor	2aa154
	StereotypeCBorderColor	092137
	StereotypeEBackgroundColor	2aa154
	StereotypeEBorderColor	092137
	StereotypeIBackgroundColor	2aa154
	StereotypeIBorderColor	092137
	StereotypeNBackgroundColor	2aa154
	StereotypeNBorderColor	092137
	StorageBackgroundColor	2aa154
	StorageBorderColor	092137
	StorageFontColor	092137
	StorageFontName	Arial
	StorageFontSize	18
	StorageFontStyle	normal 
	StorageStereotypeFontColor	092137
	StorageStereotypeFontName	Arial
	StorageStereotypeFontSize	18
	StorageStereotypeFontStyle	normal 
	Style	normal 
	SwimlaneBorderColor	092137
	SwimlaneBorderThickness	2
	SwimlaneTitleBackgroundColor	2aa154
	SwimlaneTitleFontColor	092137
	SwimlaneTitleFontName	Arial
	SwimlaneTitleFontSize	18
	SwimlaneTitleFontStyle	normal 
	TabSize	3
	TimingFontColor	092137
	TimingFontName	Arial
	TimingFontSize	18
	TimingFontStyle	normal 
	TitleBackgroundColor	2aa154
	TitleBorderColor	092137
	TitleBorderRoundCorner	TRUE
	TitleBorderThickness	2
	TitleFontColor	092137
	TitleFontName	Arial
	TitleFontSize	18
	TitleFontStyle	normal 
	UsecaseBackgroundColor	2aa154
	UsecaseBorderColor	092137
	UsecaseBorderThickness	2
	UsecaseFontColor	092137
	UsecaseFontName	Arial
	UsecaseFontSize	18
	UsecaseFontStyle	normal 
	UsecaseStereotypeFontColor	092137
	UsecaseStereotypeFontName	Arial
	UsecaseStereotypeFontSize	18
	UsecaseStereotypeFontStyle	normal 
}