sprite $Avtex [16x16/16] {
FFFFFFFFFFFFFFFF
FFF000000FFFFFFF
FFFF000000FFFFFF
FFFFF000000FFFFF
FFFFFF000000FFFF
FFFFFFF000000FFF
FFFFFFFF000000FF
FFFFFFFFFFFFFFFF
FFFFFFFF000000FF
FFFFFFF000000FFF
FFFFFF000000FFFF
FFFFF000000FFFFF
FFFF000000FFFFFF
FFF000000FFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
}

!$AvtexBlue = "092137"
!$AvtexGreen = "2aa154"
!$AvtexBackGround = "White"

skinparam {
	ActivityBackgroundColor	$AvtexGreen
	ActivityBarColor	Green
	ActivityBorderColor	$AvtexBlue
	ActivityBorderThickness	2
	ActivityDiamondBackgroundColor	$AvtexGreen
	ActivityDiamondBorderColor	$AvtexBlue
	ActivityDiamondFontColor	$AvtexBlue
	ActivityDiamondFontName	Arial
	ActivityDiamondFontSize	18
	ActivityDiamondFontStyle	normal 
	ActivityEndColor	Red
	ActivityFontColor	$AvtexBlue
	ActivityFontName	Arial
	ActivityFontSize	18
	ActivityFontStyle	normal 
	ActivityStartColor	Green
	ActorBackgroundColor	$AvtexGreen
	ActorBorderColor	$AvtexBlue
	ActorFontColor	$AvtexBlue
	ActorFontName	Arial
	ActorFontSize	18
	ActorFontStyle	normal 
	ActorStereotypeFontColor	$AvtexBlue
	ActorStereotypeFontName	Arial
	ActorStereotypeFontSize	18
	ActorStereotypeFontStyle	normal 
	AgentBackgroundColor	$AvtexGreen
	AgentBorderColor	$AvtexBlue
	AgentBorderThickness	2
	AgentFontColor	$AvtexBlue
	AgentFontName	Arial
	AgentFontSize	18
	AgentFontStyle	normal 
	AgentStereotypeFontColor	$AvtexBlue
	AgentStereotypeFontName	Arial
	AgentStereotypeFontSize	18
	AgentStereotypeFontStyle	normal 
	ArchimateBackgroundColor	$AvtexGreen
	ArchimateBorderColor	$AvtexBlue
	ArchimateBorderThickness	2
	ArchimateFontColor	$AvtexBlue
	ArchimateFontName	Arial
	ArchimateFontSize	18
	ArchimateFontStyle	normal 
	ArchimateStereotypeFontColor	$AvtexBlue
	ArchimateStereotypeFontName	Arial
	ArchimateStereotypeFontSize	18
	ArchimateStereotypeFontStyle	normal 
	ArrowColor	$AvtexBlue
	ArrowFontColor	$AvtexBlue
	ArrowFontName	Arial
	ArrowFontSize	18
	ArrowFontStyle	normal 
	ArrowHeadColor	$AvtexBlue
	ArrowLollipopColor	$AvtexBlue
	ArrowThickness	2
	ArtifactBackgroundColor	$AvtexGreen
	ArtifactBorderColor	$AvtexBlue
	ArtifactFontColor	$AvtexBlue
	ArtifactFontName	Arial
	ArtifactFontSize	18
	ArtifactFontStyle	normal 
	ArtifactStereotypeFontColor	$AvtexBlue
	ArtifactStereotypeFontName	Arial
	ArtifactStereotypeFontSize	18
	ArtifactStereotypeFontStyle	normal 
	BackgroundColor	White
	BiddableBackgroundColor	$AvtexGreen
	BiddableBorderColor	$AvtexBlue
	BoundaryBackgroundColor	$AvtexGreen
	BoundaryBorderColor	$AvtexBlue
	BoundaryFontColor	$AvtexBlue
	BoundaryFontName	Arial
	BoundaryFontSize	18
	BoundaryFontStyle	normal 
	BoundaryStereotypeFontColor	$AvtexBlue
	BoundaryStereotypeFontName	Arial
	BoundaryStereotypeFontSize	18
	BoundaryStereotypeFontStyle	normal 
	BoxPadding	10
	CaptionFontColor	$AvtexBlue
	CaptionFontName	Arial
	CaptionFontSize	18
	CaptionFontStyle	normal 
	CardBackgroundColor	$AvtexGreen
	CardBorderColor	$AvtexBlue
	CardBorderThickness	2
	CardFontColor	$AvtexBlue
	CardFontName	Arial
	CardFontSize	18
	CardFontStyle	normal 
	CardStereotypeFontColor	$AvtexBlue
	CardStereotypeFontName	Arial
	CardStereotypeFontSize	18
	CardStereotypeFontStyle	normal 
	CircledCharacterFontColor	$AvtexBlue
	CircledCharacterFontName	Arial
	CircledCharacterFontSize	18
	CircledCharacterFontStyle	normal 
	ClassAttributeFontColor	$AvtexBlue
	ClassAttributeFontName	Arial
	ClassAttributeFontSize	18
	ClassAttributeFontStyle	normal 
	ClassAttributeIconSize	12
	ClassBackgroundColor	$AvtexGreen
	ClassBorderColor	$AvtexBlue
	ClassBorderThickness	2
	ClassFontColor	$AvtexBlue
	ClassFontName	Arial
	ClassFontSize	18
	ClassFontStyle	normal 
	ClassHeaderBackgroundColor	$AvtexGreen
	ClassStereotypeFontColor	$AvtexBlue
	ClassStereotypeFontName	Arial
	ClassStereotypeFontSize	18
	ClassStereotypeFontStyle	normal 
	CloudBackgroundColor	white
	CloudBorderColor	$AvtexBlue
	CloudFontColor	$AvtexBlue
	CloudFontName	Arial
	CloudFontSize	18
	CloudFontStyle	normal 
	CloudStereotypeFontColor	$AvtexBlue
	CloudStereotypeFontName	Arial
	CloudStereotypeFontSize	18
	CloudStereotypeFontStyle	normal 
	CollectionsBackgroundColor	$AvtexGreen
	CollectionsBorderColor	$AvtexBlue
	ColorArrowSeparationSpace	$AvtexBlue
	ComponentBackgroundColor	$AvtexGreen
	ComponentBorderColor	$AvtexBlue
	ComponentBorderThickness	2
	ComponentFontColor	$AvtexBlue
	ComponentFontName	Arial
	ComponentFontSize	18
	ComponentFontStyle	normal 
	ComponentStereotypeFontColor	$AvtexBlue
	ComponentStereotypeFontName	Arial
	ComponentStereotypeFontSize	18
	ComponentStereotypeFontStyle	normal 
	ComponentStyle	normal 
	ConditionEndStyle	normal 
	ConditionStyle	normal 
	ControlBackgroundColor	$AvtexGreen
	ControlBorderColor	$AvtexBlue
	ControlFontColor	$AvtexBlue
	ControlFontName	Arial
	ControlFontSize	18
	ControlFontStyle	normal 
	ControlStereotypeFontColor	$AvtexBlue
	ControlStereotypeFontName	Arial
	ControlStereotypeFontSize	18
	ControlStereotypeFontStyle	normal 
	DatabaseBackgroundColor	White
	DatabaseBorderColor	$AvtexBlue
	DatabaseFontColor	$AvtexBlue
	DatabaseFontName	Arial
	DatabaseFontSize	18
	DatabaseFontStyle	normal 
	DatabaseStereotypeFontColor	$AvtexBlue
	DatabaseStereotypeFontName	Arial
	DatabaseStereotypeFontSize	18
	DatabaseStereotypeFontStyle	normal 
	DefaultFontColor	$AvtexBlue
	DefaultFontName	Arial
	DefaultFontSize	18
	DefaultFontStyle	normal 
	DefaultMonospacedFontName	Arial
	DefaultTextAlignment	center
	DesignedBackgroundColor	$AvtexGreen
	DesignedBorderColor	$AvtexBlue
	DesignedDomainBorderThickness	2
	DesignedDomainFontColor	$AvtexBlue
	DesignedDomainFontName	Arial
	DesignedDomainFontSize	18
	DesignedDomainFontStyle	normal 
	DesignedDomainStereotypeFontColor	$AvtexBlue
	DesignedDomainStereotypeFontName	Arial
	DesignedDomainStereotypeFontSize	18
	DesignedDomainStereotypeFontStyle	normal 
	DiagramBorderColor	$AvtexBlue
	DiagramBorderThickness	2
	DomainBackgroundColor	$AvtexGreen
	DomainBorderColor	$AvtexBlue
	DomainBorderThickness	2
	DomainFontColor	$AvtexBlue
	DomainFontName	Arial
	DomainFontSize	18
	DomainFontStyle	normal 
	DomainStereotypeFontColor	$AvtexBlue
	DomainStereotypeFontName	Arial
	DomainStereotypeFontSize	18
	DomainStereotypeFontStyle	normal 
	EntityBackgroundColor	$AvtexGreen
	EntityBorderColor	$AvtexBlue
	EntityFontColor	$AvtexBlue
	EntityFontName	Arial
	EntityFontSize	18
	EntityFontStyle	normal 
	EntityStereotypeFontColor	$AvtexBlue
	EntityStereotypeFontName	Arial
	EntityStereotypeFontSize	18
	EntityStereotypeFontStyle	normal 
	EnumBackgroundColor	$AvtexGreen
	FileBackgroundColor	$AvtexGreen
	FileBorderColor	$AvtexBlue
	FileFontColor	$AvtexBlue
	FileFontName	Arial
	FileFontSize	18
	FileFontStyle	normal 
	FileStereotypeFontColor	$AvtexBlue
	FileStereotypeFontName	Arial
	FileStereotypeFontSize	18
	FileStereotypeFontStyle	normal 
	FolderBackgroundColor	$AvtexGreen
	FolderBorderColor	$AvtexBlue
	FolderFontColor	$AvtexBlue
	FolderFontName	Arial
	FolderFontSize	18
	FolderFontStyle	normal 
	FolderStereotypeFontColor	$AvtexBlue
	FolderStereotypeFontName	Arial
	FolderStereotypeFontSize	18
	FolderStereotypeFontStyle	normal 
	FooterFontColor	$AvtexBlue
	FooterFontName	Arial
	FooterFontSize	18
	FooterFontStyle	normal 
	FrameBackgroundColor	$AvtexGreen
	FrameBorderColor	$AvtexBlue
	FrameFontColor	$AvtexBlue
	FrameFontName	Arial
	FrameFontSize	18
	FrameFontStyle	normal 
	FrameStereotypeFontColor	$AvtexBlue
	FrameStereotypeFontName	Arial
	FrameStereotypeFontSize	18
	FrameStereotypeFontStyle	normal 
	HeaderFontColor	$AvtexBlue
	HeaderFontName	Arial
	HeaderFontSize	18
	HeaderFontStyle	normal 
	HyperlinkColor	$AvtexBlue
	IconIEMandatoryColor	$AvtexBlue
	IconPackageBackgroundColor	$AvtexGreen
	IconPackageColor	$AvtexBlue
	IconPrivateBackgroundColor	$AvtexGreen
	IconPrivateColor	$AvtexBlue
	IconProtectedBackgroundColor	$AvtexGreen
	IconProtectedColor	$AvtexBlue
	IconPublicBackgroundColor	$AvtexGreen
	IconPublicColor	$AvtexBlue
	InterfaceBackgroundColor	$AvtexGreen
	InterfaceBorderColor	$AvtexBlue
	InterfaceFontColor	$AvtexBlue
	InterfaceFontName	Arial
	InterfaceFontSize	18
	InterfaceFontStyle	normal 
	InterfaceStereotypeFontColor	$AvtexBlue
	InterfaceStereotypeFontName	Arial
	InterfaceStereotypeFontSize	18
	InterfaceStereotypeFontStyle	normal 
	LegendBackgroundColor	$AvtexGreen
	LegendBorderColor	$AvtexBlue
	LegendBorderThickness	2
	LegendFontColor	$AvtexBlue
	LegendFontName	Arial
	LegendFontSize	18
	LegendFontStyle	normal 
	LexicalBackgroundColor	$AvtexGreen
	LexicalBorderColor	$AvtexBlue
	MachineBackgroundColor	$AvtexGreen
	MachineBorderColor	$AvtexBlue
	MachineBorderThickness	2
	MachineFontColor	$AvtexBlue
	MachineFontName	Arial
	MachineFontSize	18
	MachineFontStyle	normal 
	MachineStereotypeFontColor	$AvtexBlue
	MachineStereotypeFontName	Arial
	MachineStereotypeFontSize	18
	MachineStereotypeFontStyle	normal 
	NodeBackgroundColor	White
	NodeBorderColor	$AvtexBlue
	NodeFontColor	$AvtexBlue
	NodeFontName	Arial
	NodeFontSize	18
	NodeFontStyle	normal 
	NodeStereotypeFontColor	$AvtexBlue
	NodeStereotypeFontName	Arial
	NodeStereotypeFontSize	18
	NodeStereotypeFontStyle	normal 
	NoteBackgroundColor	$AvtexGreen
	NoteBorderColor	$AvtexBlue
	NoteBorderThickness	2
	NoteFontColor	$AvtexBlue
	NoteFontName	Arial
	NoteFontSize	18
	NoteFontStyle	normal 
	NoteShadowing	TRUE
	NoteTextAlignment	Center
	ObjectAttributeFontColor	$AvtexBlue
	ObjectAttributeFontName	Arial
	ObjectAttributeFontSize	18
	ObjectAttributeFontStyle	normal 
	ObjectBackgroundColor	$AvtexGreen
	ObjectBorderColor	$AvtexBlue
	ObjectBorderThickness	2
	ObjectFontColor	$AvtexBlue
	ObjectFontName	Arial
	ObjectFontSize	18
	ObjectFontStyle	normal 
	ObjectStereotypeFontColor	$AvtexBlue
	ObjectStereotypeFontName	Arial
	ObjectStereotypeFontSize	18
	ObjectStereotypeFontStyle	normal 
	PackageBackgroundColor	white
	PackageBorderColor	$AvtexBlue
	PackageBorderThickness	2
	PackageFontColor	$AvtexBlue
	PackageFontName	Arial
	PackageFontSize	18
	PackageFontStyle	normal 
	PackageStereotypeFontColor	$AvtexBlue
	PackageStereotypeFontName	Arial
	PackageStereotypeFontSize	18
	PackageStereotypeFontStyle	normal 
	PackageStyle	Bold
	PackageTitleAlignment	left
	PageBorderColor	$AvtexBlue
	PageExternalColor	$AvtexBlue
	PageMargin	5
	ParticipantBackgroundColor	$AvtexGreen
	ParticipantBorderColor	$AvtexBlue
	ParticipantFontColor	$AvtexBlue
	ParticipantFontName	Arial
	ParticipantFontSize	18
	ParticipantFontStyle	normal 
	ParticipantPadding	100
	ParticipantStereotypeFontColor	$AvtexBlue
	ParticipantStereotypeFontName	Arial
	ParticipantStereotypeFontSize	18
	ParticipantStereotypeFontStyle	normal 
	PartitionBackgroundColor	$AvtexGreen
	PartitionBorderColor	$AvtexBlue
	PartitionBorderThickness	2
	PartitionFontColor	$AvtexBlue
	PartitionFontName	Arial
	PartitionFontSize	18
	PartitionFontStyle	normal 
	PathHoverColor	$AvtexBlue
	QueueBackgroundColor	$AvtexGreen
	QueueBorderColor	$AvtexBlue
	QueueBorderThickness	2
	QueueFontColor	$AvtexBlue
	QueueFontName	Arial
	QueueFontSize	18
	QueueFontStyle	normal 
	QueueStereotypeFontColor	$AvtexBlue
	QueueStereotypeFontName	Arial
	QueueStereotypeFontSize	18
	QueueStereotypeFontStyle	normal 
	RectangleBackgroundColor	$AvtexGreen
	RectangleBorderColor	$AvtexBlue
	RectangleBorderThickness	2
	RectangleFontColor	$AvtexBlue
	RectangleFontName	Arial
	RectangleFontSize	18
	RectangleFontStyle	normal 
	RectangleStereotypeFontColor	$AvtexBlue
	RectangleStereotypeFontName	Arial
	RectangleStereotypeFontSize	18
	RectangleStereotypeFontStyle	normal 
	RequirementBackgroundColor	$AvtexGreen
	RequirementBorderColor	$AvtexBlue
	RequirementBorderThickness	2
	RequirementFontColor	$AvtexBlue
	RequirementFontName	Arial
	RequirementFontSize	18
	RequirementFontStyle	normal 
	RequirementStereotypeFontColor	$AvtexBlue
	RequirementStereotypeFontName	Arial
	RequirementStereotypeFontSize	18
	RequirementStereotypeFontStyle	normal 
	RoundCorner	TRUE
	SequenceActorBorderThickness	2
	SequenceArrowThickness	2
	SequenceBoxBackgroundColor	$AvtexGreen
	SequenceBoxBorderColor	$AvtexBlue
	SequenceBoxFontColor	$AvtexBlue
	SequenceBoxFontName	Arial
	SequenceBoxFontSize	18
	SequenceBoxFontStyle	normal 
	SequenceDelayFontColor	$AvtexBlue
	SequenceDelayFontName	Arial
	SequenceDelayFontSize	18
	SequenceDelayFontStyle	normal 
	SequenceDividerBackgroundColor	$AvtexGreen
	SequenceDividerBorderColor	$AvtexBlue
	SequenceDividerBorderThickness	2
	SequenceDividerFontColor	$AvtexBlue
	SequenceDividerFontName	Arial
	SequenceDividerFontSize	18
	SequenceDividerFontStyle	normal 
	SequenceGroupBackgroundColor	$AvtexGreen
	SequenceGroupBodyBackgroundColor	$AvtexGreen
	SequenceGroupBorderColor	$AvtexBlue
	SequenceGroupBorderThickness	2
	SequenceGroupFontColor	$AvtexBlue
	SequenceGroupFontName	Arial
	SequenceGroupFontSize	18
	SequenceGroupFontStyle	normal 
	SequenceGroupHeaderFontColor	$AvtexBlue
	SequenceGroupHeaderFontName	Arial
	SequenceGroupHeaderFontSize	18
	SequenceGroupHeaderFontStyle	normal 
	SequenceLifeLineBackgroundColor	$AvtexGreen
	SequenceLifeLineBorderColor	$AvtexBlue
	SequenceLifeLineBorderThickness	2
	SequenceMessageAlignment	center
	SequenceMessageTextAlignment	center
	SequenceNewpageSeparatorColor	$AvtexBlue
	SequenceParticipantBorderThickness	2
	SequenceReferenceBackgroundColor	$AvtexGreen
	SequenceReferenceBorderColor	$AvtexBlue
	SequenceReferenceBorderThickness	2
	SequenceReferenceFontColor	$AvtexBlue
	SequenceReferenceFontName	Arial
	SequenceReferenceFontSize	18
	SequenceReferenceFontStyle	normal 
	SequenceReferenceHeaderBackgroundColor	$AvtexGreen
	SequenceStereotypeFontColor	$AvtexBlue
	SequenceStereotypeFontName	Arial
	SequenceStereotypeFontSize	18
	SequenceStereotypeFontStyle	normal 
	Shadowing	TRUE
	StackBackgroundColor	$AvtexGreen
	StackBorderColor	$AvtexBlue
	StackFontColor	$AvtexBlue
	StackFontName	Arial
	StackFontSize	18
	StackFontStyle	normal 
	StackStereotypeFontColor	$AvtexBlue
	StackStereotypeFontName	Arial
	StackStereotypeFontSize	18
	StackStereotypeFontStyle	normal 
	StateAttributeFontColor	$AvtexBlue
	StateAttributeFontName	Arial
	StateAttributeFontSize	18
	StateAttributeFontStyle	normal 
	StateBackgroundColor	$AvtexGreen
	StateBorderColor	$AvtexBlue
	StateEndColor	$AvtexBlue
	StateFontColor	$AvtexBlue
	StateFontName	Arial
	StateFontSize	18
	StateFontStyle	normal 
	StateStartColor	$AvtexBlue
	StereotypeABackgroundColor	$AvtexGreen
	StereotypeABorderColor	$AvtexBlue
	StereotypeCBackgroundColor	$AvtexGreen
	StereotypeCBorderColor	$AvtexBlue
	StereotypeEBackgroundColor	$AvtexGreen
	StereotypeEBorderColor	$AvtexBlue
	StereotypeIBackgroundColor	$AvtexGreen
	StereotypeIBorderColor	$AvtexBlue
	StereotypeNBackgroundColor	$AvtexGreen
	StereotypeNBorderColor	$AvtexBlue
	StorageBackgroundColor	$AvtexGreen
	StorageBorderColor	$AvtexBlue
	StorageFontColor	$AvtexBlue
	StorageFontName	Arial
	StorageFontSize	18
	StorageFontStyle	normal 
	StorageStereotypeFontColor	$AvtexBlue
	StorageStereotypeFontName	Arial
	StorageStereotypeFontSize	18
	StorageStereotypeFontStyle	normal 
	Style	normal 
	SwimlaneBorderColor	$AvtexBlue
	SwimlaneBorderThickness	2
	SwimlaneTitleBackgroundColor	$AvtexGreen
	SwimlaneTitleFontColor	$AvtexBlue
	SwimlaneTitleFontName	Arial
	SwimlaneTitleFontSize	18
	SwimlaneTitleFontStyle	normal 
	TabSize	3
	TimingFontColor	$AvtexBlue
	TimingFontName	Arial
	TimingFontSize	18
	TimingFontStyle	normal 
	TitleBackgroundColor	$AvtexGreen
	TitleBorderColor	$AvtexBlue
	TitleBorderRoundCorner	TRUE
	TitleBorderThickness	2
	TitleFontColor	$AvtexBlue
	TitleFontName	Arial
	TitleFontSize	18
	TitleFontStyle	normal 
	UsecaseBackgroundColor	$AvtexGreen
	UsecaseBorderColor	$AvtexBlue
	UsecaseBorderThickness	2
	UsecaseFontColor	$AvtexBlue
	UsecaseFontName	Arial
	UsecaseFontSize	18
	UsecaseFontStyle	normal 
	UsecaseStereotypeFontColor	$AvtexBlue
	UsecaseStereotypeFontName	Arial
	UsecaseStereotypeFontSize	18
	UsecaseStereotypeFontStyle	normal 
}
